CREATE TABLE IF NOT EXISTS PRICE_ENTITY (
  ID_PRICE_ENTITY  int NOT NULL,
  BRAND_ID int NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE_LIST  int NOT NULL,
  PRODUCT_ID  varchar NOT NULL,
  PRIORITY  varchar NOT NULL,
  PRICE  double not null,
  CURR  varchar  not null );